### PR TITLE
feat(GitOpsConfig): release apiVersion 2

### PR DESCRIPTION
**Pull request by christiansiegel**

### CODE REVIEW

**Comment by joachimprinzbach** [comment]
I did some tests: 
https://github.com/baloise-incubator/gitops-nginx-demo/pull/56
https://github.com/baloise-incubator/gitops-nginx-demo/pull/55
https://github.com/baloise-incubator/gitops-nginx-demo/pull/54

The one with the short preview hash is not reachable (ns and route seem to be fine, is healthy synce), i am still looking into it. Rest (no api version, beta api version) seems to work fine.

**Review by joachimprinzbach — APPROVED** [review]

**Comment by joachimprinzbach** [comment]
Works like a charm - awesome work @christiansiegel! 

I would add the generator and also the changes between the versions somewhere in the docs and maybe also in the release notes?

What about the following release procedure? 
- release this change as 5.0.0 with API version 2 -> is a compatibility release that makes migrating to v2 easier
- release 6.0.0 with API version 1 and unversioned config support removed as a breaking change

**Comment by christiansiegel** [comment]
I amended the previous commit with
- updated commit message (major release + mentioned converter)
- added info box to doc

**Comment by joachimprinzbach** [comment]
Great, thx a lot - ready to release :-)

**Pull request merged**
